<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'Crazy Rich Asians',
                'author' => 'Kevin Kwan',
                'isbn' => '9780385536977',
                'description' => 'Envisioning a summer vacation in the humble Singapore home of a boy she hopes to marry, Chinese American Rachel Chu is unexpectedly introduced to a rich and scheming clan that strongly opposes their son\'s relationship with an American girl.',
                'genre' => 'Fiction, Romance, Contemporary, Drama',
                'publication_year' => 2013,
                'price' => 12.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1364852559i/16085481.jpg',
            ],
            [
                'title' => 'The Lightning Thief',
                'author' => 'Rick Riordan',
                'isbn' => '9780786838653',
                'description' => 'After learning that he is the son of a mortal woman and Poseidon, god of the sea, twelve-year-old Percy is sent to a summer camp for demigods like himself, and joins his new friends on a quest to prevent a war between the gods.',
                'genre' => 'Fantasy, Young Adult, Mythology, Fiction',
                'publication_year' => 2005,
                'price' => 10.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1684776677i/123675190.jpg',
            ],
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'isbn' => '9780439023481',
                'description' => 'Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister\'s place in the Games. But Katniss has been close to dead before-and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weigh survival against humanity and life against love.',
                'genre' => 'Dystopia, Young Adult, Fantasy, Adventure',
                'publication_year' => 2008,
                'price' => 11.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1586722975i/2767052.jpg',
            ],
            [
                'title' => 'The Seven Husbands of Evelyn Hugo',
                'author' => 'Taylor Jenkins Reid',
                'isbn' => '9781501171349',
                'description' => 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself. Why her? Why now?',
                'genre' => 'Historical Fiction, Romance, Drama, LGBT',
                'publication_year' => 2017,
                'price' => 13.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1664458703i/32620332.jpg',
            ],
            [
                'title' => 'Gone Girl',
                'author' => 'Gillian Flynn',
                'isbn' => '9780307588371',
                'description' => 'Nick Dunne’s wife Amy suddenly disappears. The police suspect Nick. Amy\'s friends reveal that she was afraid of him, that she kept secrets from him. He swears it isn\'t true. A police examination of his computer shows strange searches. He says they weren\'t made by him. And then there are the persistent calls on his mobile phone. So what happened to Nick\'s beautiful wife?',
                'genre' => 'Fiction, Mystery, Thriller, Crime',
                'publication_year' => 2012,
                'price' => 14.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554086139i/19288043.jpg',
            ],
            [
                'title' => 'Little Women',
                'author' => 'Louisa May Alcott',
                'isbn' => '9780147514011',
                'description' => 'Louisa May Alcott\'s classic novel, set during the Civil War, has always captivated even the most reluctant readers. Little girls, especially, love following the adventures of the four March sisters: Meg, Beth, Amy, and most of all, the tomboy Jo, as they experience the joys and disappointments, tragedies and triumphs, of growing up.',
                'genre' => 'Classics, Fiction, Historical Fiction, Young Adult',
                'publication_year' => 1868,
                'price' => 9.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1562690475i/1934.jpg',
            ],
            [
                'title' => 'The Little Prince',
                'author' => 'Antoine de Saint-Exupéry',
                'isbn' => '9780156012195',
                'description' => 'A pilot stranded in the desert awakes one morning to see, standing before him, the most extraordinary little fellow. "Please," asks the stranger, "draw me a sheep." And the pilot realizes that when life\'s events are too difficult to understand, there is no choice but to succumb to their mysteries. He pulls out pencil and paper... And thus begins this wise and enchanting fable that, in teaching the secret of what is really important in life, has changed forever the world for its readers.',
                'genre' => 'Classics, Fiction, Fantasy, Childrens',
                'publication_year' => 1943,
                'price' => 10.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1367545443i/157993.jpg',
            ],
            [
                'title' => 'The Martian',
                'author' => 'Andy Weir',
                'isbn' => '9780553418026',
                'description' => 'Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he’s sure he’ll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he’s alive—and even if he could get word out, his supplies would be gone long before a rescue could arrive. But Mark isn’t ready to give up yet. Drawing on his ingenuity, his engineering skills — and a relentless, dogged refusal to quit — he steadfastly confronts one seemingly insurmountable obstacle after the next. Will his resourcefulness be enough to overcome the impossible odds against him?',
                'genre' => 'Science Fiction, Adventure, Spaces',
                'publication_year' => 2011,
                'price' => 14.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1413706054i/18007564.jpg',
            ],
            [
                'title' => 'Lolita',
                'author' => 'Vladimir Nabokov',
                'isbn' => '9780679723165',
                'description' => 'Awe and exhilaration—along with heartbreak and mordant wit—abound in Lolita, which tells the story of the aging Humbert Humbert\'s obsession for the nymphet Dolores Haze. Lolita is also the story of a hypercivilized European colliding with the cheerful barbarism of postwar America. Most of all, it is a meditation on love—love as outrage and hallucination, madness and transformation.',
                'genre' => 'Classics, Fiction',
                'publication_year' => 1955,
                'price' => 12.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1439610958i/6048235.jpg',
            ],
            [
                'title' => 'The Count of Monte Cristo',
                'author' => 'Alexandre Dumas',
                'isbn' => '9780140449266',
                'description' => 'Thrown in prison for a crime he has not committed, Edmond Dantes is confined to the grim fortress of If. There he learns of a great hoard of treasure hidden on the Isle of Monte Cristo and becomes determined not only to escape but to unearth the treasure and use it to plot the destruction of the three men responsible for his incarceration.',
                'genre' => 'Classics, Historical Fiction, Adventure',
                'publication_year' => 1846,
                'price' => 11.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1724863997i/7126.jpg',
            ],
            [
                'title' => 'The Song of Achilles',
                'author' => 'Madeline Miller',
                'isbn' => '9780062060624',
                'description' => 'Achilles, "the best of all the Greeks," son of the cruel sea goddess Thetis and the legendary king Peleus, is strong, swift, and beautiful, irresistible to all who meet him. Patroclus is an awkward young prince, exiled from his homeland after an act of shocking violence. Brought together by chance, they forge an inseparable bond, despite risking the gods\' wrath. They are trained by the centaur Chiron in the arts of war and medicine, but when word comes that Helen of Sparta has been kidnapped, all the heroes of Greece are called upon to lay siege to Troy in her name. Seduced by the promise of a glorious destiny, Achilles joins their cause, and torn between love and fear for his friend, Patroclus follows. Little do they know that the cruel Fates will test them both as never before and demand a terrible sacrifice.',
                'genre' => 'Mythology, Romance, Fiction, LGBT',
                'publication_year' => 2011,
                'price' => 13.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1357177533i/13623848.jpg',
            ],
            [
                'title' => 'Dracula',
                'author' => 'Bram Stoker',
                'isbn' => '9780141439484',
                'description' => 'When Jonathan Harker visits Transylvania to help Count Dracula with the purchase of a London house, he makes a series of horrific discoveries about his client. Soon afterwards, various bizarre incidents unfold in England: an apparently unmanned ship is wrecked off the coast of Whitby; a young woman discovers strange puncture marks on her neck; and the inmate of a lunatic asylum raves about the \'Master\' and his imminent arrival.',
                'genre' => 'Classics, Horror, Fiction, Gothic',
                'publication_year' => 1897,
                'price' => 10.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1745309794i/588495.jpg',
            ],
            [
                'title' => 'Twilight',
                'author' => 'Stephenie Meyer',
                'isbn' => '9780316015844',
                'description' => 'First, Edward was a vampire. Second, there was a part of him - and I didn\'t know how dominant that part might be - that thirsted for my blood. And third, I was unconditionally and irrevocably in love with him.',
                'genre' => 'Fantasy, Young Adult, Romance, Fiction',
                'publication_year' => 2005,
                'price' => 10.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1700522826i/41865.jpg',
            ],
            [
                'title' => 'Divergent',
                'author' => 'Veronica Roth',
                'isbn' => '9780062387249',
                'description' => 'In Beatrice Prior\'s dystopian Chicago world, society is divided into five factions, each dedicated to the cultivation of a particular virtue—Candor (the honest), Abnegation (the selfless), Dauntless (the brave), Amity (the peaceful), and Erudite (the intelligent). On an appointed day of every year, all sixteen-year-olds must select the faction to which they will devote the rest of their lives. For Beatrice, the decision is between staying with her family and being who she really is—she can\'t have both. So she makes a choice that surprises everyone, including herself.',
                'genre' => 'Young Adult, Dystopia, Fantasy, Fiction',
                'publication_year' => 2011,
                'price' => 11.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1618526890i/13335037.jpg',
            ],
            [
                'title' => 'Anne of Green Gables',
                'author' => 'L.M. Montgomery',
                'isbn' => '9780553213133',
                'description' => 'Anne Shirley, an eleven-year-old orphan, has arrived in this verdant corner of Prince Edward Island only to discover that the Cuthberts—elderly Matthew and his stern sister, Marilla—want to adopt a boy, not a feisty redheaded girl. But before they can send her back, Anne—who simply must have more scope for her imagination and a real home—wins them over completely.',
                'genre' => 'Classics, Fiction, Young Adult, Childrens',
                'publication_year' => 1908,
                'price' => 9.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1656778824i/763588.jpg',
            ],
            [
                'title' => 'Coraline',
                'author' => 'Neil Gaiman',
                'isbn' => '9780385733451',
                'description' => 'In Coraline\'s family\'s new flat are twenty-one windows and fourteen doors. Thirteen of the doors open and close. The fourteenth is locked, and on the other side is only a brick wall, until the day Coraline unlocks the door to find a passage to another flat in another house just like her own. Only it\'s different. At first, things seem marvelous in the other flat. The food is better. The toy box is filled with wind-up angels that flutter around the bedroom, books whose pictures writhe and crawl and shimmer, little dinosaur skulls that chatter their teeth. But there\'s another mother, and another father, and they want Coraline to stay with them and be their little girl. They want to change her and never let her go.',
                'genre' => 'Fantasy, Horror, Fiction, Young Adult',
                'publication_year' => 2002,
                'price' => 10.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1621336504i/474073.jpg',
            ],
            [
                'title' => 'The Maze Runner',
                'author' => 'James Dashner',
                'isbn' => '9780385737954',
                'description' => 'If you ain’t scared, you ain’t human. When Thomas wakes up in the lift, the only thing he can remember is his name. He’s surrounded by strangers—boys whose memories are also gone. Nice to meet ya, shank. Welcome to the Glade. Outside the towering stone walls that surround the Glade is a limitless, ever-changing maze. It’s the only way out—and no one’s ever made it through alive. Everything is going to change. Then a girl arrives. The first girl ever. And the message she delivers is terrifying.',
                'genre' => 'Young Adult, Dystopia, Science Fiction, Thriller',
                'publication_year' => 2009,
                'price' => 11.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1375596592i/6186357.jpg',
            ],
            [
                'title' => 'Bridge to Terabithia',
                'author' => 'Katherine Paterson',
                'isbn' => '9780064401845',
                'description' => 'Jess Aarons has been practicing all summer so he can be the fastest runner in the fifth grade. And he almost is, until the new girl in school, Leslie Burke, outpaces him. The two become fast friends and spend most days in the woods behind Leslie\'s house, where they invent an enchanted land called Terabithia. One morning, Leslie goes to Terabithia without Jess and a tragedy occurs. It will take the love of his family and the strength that Leslie has given him for Jess to be able to deal with his grief.',
                'genre' => 'Fiction, Young Adult, Classics, Fantasy',
                'publication_year' => 1977,
                'price' => 7.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1532478367i/40940121.jpg',
            ],
            [
                'title' => 'The Queen’s Gambit',
                'author' => 'Walter Tevis',
                'isbn' => '9780345804047',
                'description' => 'When she is sent to an orphanage at the age of eight, Beth Harmon soon discovers two ways to escape her surroundings, albeit fleetingly: playing chess and taking the little green pills given to her and the other children to keep them subdued. Before long, it becomes apparent that hers is a prodigious talent, and as she progresses to the top of the US chess rankings she is able to forge a new life for herself. But she can never quite overcome her urge to self-destruct. For Beth, there’s more at stake than merely winning and losing.',
                'genre' => 'Fiction, Classics, Chess, Historical Fiction',
                'publication_year' => 1983,
                'price' => 11.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388265750i/62022.jpg',
            ],
            [
                'title' => 'Carmilla',
                'author' => 'J. Sheridan Le Fanu',
                'isbn' => '9780140437841',
                'description' => 'In an isolated castle deep in the Austrian forest, Laura leads a solitary life with only her ailing father for company. Until one moonlit night, a horse-drawn carriage crashes into view, carrying an unexpected guest – the beautiful Carmilla. So begins a feverish friendship between Laura and her mysterious, entrancing companion. But as Carmilla becomes increasingly strange and volatile, prone to eerie nocturnal wanderings, Laura finds herself tormented by nightmares and growing weaker by the day.',
                'genre' => 'Classics, Horror, Vampires, LGBT',
                'publication_year' => 1872,
                'price' => 10.99,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657795822i/48037.jpg',
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
